name: Keep WanderStay Alive

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  workflow_dispatch:        # Allows you to run it manually to test

jobs:
  wake_up:
    runs-on: ubuntu-latest
    steps:
      - name: Ping App
        run: |
          curl -I -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" https://wanderstay.streamlit.app/
          
